### ISSUE TITLE
Include params for company/news(full)

### ISSUE THREAD

**Issue by DeKleineKobini** [Torn-Playground/tornapi-documentation#60]

**Comment by GenShinigami** [comment]
`https://api.torn.com/company/?selections=newsfull&limit=1&key=[KEY]` works

`https://api.torn.com/company/?selections=newsfull&to=1659122597&key=[KEY]` continues to return data past the timestamp of 61460327

`https://api.torn.com/company/?selections=newsfull&from=1659122597&key=[KEY]` does not seem to change the calls at all.

`https://api.torn.com/company/?selections=newsfull&to=1659122597&from=1659075769&key=[KEY]` does not seem to limit the calls at all.
