### ISSUE TITLE
Map reports (faction and user) for bounty reveal.

### ISSUE THREAD

**Issue by DeKleineKobini** [Torn-Playground/tornapi-documentation#79]

**Comment by Kwack-Kwack** [comment]
```jsonc
{
	//...
	"type": "anonymousbounties",
	"report": [
		"Tamzidy [2649213] @ $40,000",
		"Crie [2176937] @ $1",
		"Crie [2176937] @ $1",
		"Armysqueaky [2567758] @ $1",
		"FIREWALL [BLOCKED] @ $100,000"
	]
	//...
},
```
Bizarre that this uses an array rather than `"report": { "anonymousbounties": string[] },` to be consistent with other reports

**Comment by DeKleineKobini** [comment]
Not mapping this one for now: <https://www.torn.com/forums.php#/p=threads&f=19&t=16329498&b=0&a=0>

**Comment by DeKleineKobini** [comment]
> ```js
> {
> 	//...
> 	"type": "anonymousbounties",
> 	"report": [
> 		"Tamzidy [2649213] @ $40,000",
> 		"Crie [2176937] @ $1",
> 		"Crie [2176937] @ $1",
> 		"Armysqueaky [2567758] @ $1",
> 		"FIREWALL [BLOCKED] @ $100,000"
> 	]
> 	//...
> },
> ```
> 
> Bizarre that this uses an array rather than `"report": { "anonymousbounties": string[] },` to be consistent with other reports

Chedburn changed the layout of new reports. Would you be able to provide that layout? If needed I'm willing to pay for the usage of job points.

I won't map the old layout, but I'll put it in writing that there is something going on in for old reports.
